on:
  push:
    branches:
      - master





jobs:
  build:
    runs-on: ubuntu-latest 


    steps:
  
      - name: 'Before'
        run: echo ls

      - uses: actions/chechout@v3
      
      - name: 'After'
        run: echo ls
