on:
  push:
    branches:
      - master





jobs:
  build:
    runs-on: ubuntu-latest 


    steps:
  
      - uses: actions/checkout@v3

      - name: "Login to Docjer Hub"
        run: docker login --username mhmoudsyd  --password dckr_pat_EGqKMEtDf7gQYQJU4tdmIbpDDwo

